# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.TextField(db_index=True, max_length=60, verbose_name='标题')),
                ('slug', models.TextField(max_length=100)),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '博客文章',
                'ordering': ('-created',),
                'verbose_name_plural': '博客文章',
            },
        ),
    ]
