# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170717_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/image/136/120/', upload_to='images/%Y/%m/%d', verbose_name='封面图片'),
        ),
    ]
