# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='/image/136/120/', upload_to='post/%Y/%m/%d'),
        ),
    ]
