# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-17 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170718_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/image/136/120/', upload_to='post/%Y/%m/%d'),
        ),
    ]
