# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170718_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d'),
        ),
    ]
