# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='简评'),
        ),
    ]
